# Generated by Django 3.2.3 on 2021-09-27 19:22

import apps.users.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='First input country code eg.(+48), then the number.', regex='^\\+?1?\\d{8,15}$')])),
                ('picture', models.ImageField(upload_to='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_users', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, apps.users.models.CreatedUpdatedMixin),
        ),
    ]
